import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import {getServerSession} from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch the user
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="mx-64">
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
      </body>
    </html>
  );
}
