import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Hydrate from "./components/Hydrate";
import { Roboto, Lobster_Two } from "next/font/google";
import { Inter } from "next/font/google";

// define main font
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const lobster = Lobster_Two({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "1Piece - The Best One Piece Figures Shope",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch the user
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`mx-4 lg:mx-64 ${roboto.className}`}>
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
